### ISSUE TITLE
generate html5:install throws undefined method `stylesheets_directory'

### ISSUE THREAD

**Issue by kieranklaassen** [sporkd/html5-rails#15]
When running `rails generate html5:install`

``` bash
/Users/kieranklaassen/Dropbox/rails/lov/lichtopverlies/config/application.rb:61:in `<class:Application>': undefined method `stylesheets_directory' for nil:NilClass (NoMethodError)
    from /Users/kieranklaassen/Dropbox/rails/lov/lichtopverlies/config/application.rb:10:in `<module:Lov>'
    from /Users/kieranklaassen/Dropbox/rails/lov/lichtopverlies/config/application.rb:9:in `<top (required)>'
    from /Users/kieranklaassen/.rvm/gems/ruby-1.9.2-p180@lov/gems/railties-3.2.0/lib/rails/commands.rb:24:in `require'
    from /Users/kieranklaassen/.rvm/gems/ruby-1.9.2-p180@lov/gems/railties-3.2.0/lib/rails/commands.rb:24:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Where can I fix this?
I am updating from the old html5-boilerplate gem.

Thanks

**Comment by kieranklaassen** [comment]
Was an old config.sass.load_paths.
